[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# depends = ['neosnippet-snippets','vim-snippets']
# on_i = 1
# on_ft = 'snippet'
# hook_source = '''
#   imap <C-k> <Plug>(neosnippet_expand_or_jump)
#   smap <C-k> <Plug>(neosnippet_expand_or_jump)
#   xmap <C-k> <Plug>(neosnippet_expand_target)
#   
#   if has('conceal')
#     set conceallevel=2 concealcursor=niv
#   endif
# '''

[[plugins]]
repo  = 'Quramy/tsuquyomi'
if = '!has("nvim")'
on_ft = 'typescript'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
	let g:indent_guides_enable_on_vim_startup=1
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','jade','pug','php','css','sass','scss']
hook_source = '''
	let g:user_emmet_leader_key='<c-e>'
	let g:user_emmet_settings = {
		\	'variables':{
		\		'lang': 'ja',
		\		'locale': 'ja-JP',
		\		'indentation': '  ',
		\	},
	\}
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'osyo-manga/vim-precious'

